---
title: "AI在社交軟體中檢測偽造頭像"
author:
  - name: "莊惠媤"
  - name: "董宸賓"
date: "2023-11-21"
description: |
  計算機概論報告整理
output:
  distill::distill_article: 
   toc: False
   theme: "css1.css"
main-color: "#0F2E3D"
# knit: pagedown::chrome_print
---

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(distill)
library(rmarkdown)
```

## The Harm of Fake Accounts to Social Communities and User

### Exploiting Public Trust in Public Figures for Scams

Facebook is filled with photos impersonating celebrities, using the names of stars and internet personalities to invite users into related investment groups, engaging in fraudulent activities

### The users no longer trust the platform, and advertisers are no longer investing in advertising.

the ongoing scams have reduced trust in Facebook, leading to a declining user base. Retaining users is now a crucial challenge. Additionally, an abundance of bots is manipulating discussions and sentiments on the platform, negatively impacting the online environment. Lastly, fake accounts are providing false feedback, impairing the effectiveness of ad targeting

## Behavior Analysis


## Image analysis

### Image Recognition Algorithm:

- Description: <br>
Advanced image recognition algorithms typically rely on deep learning and artificial intelligence to analyze key features in images, aiming to identify patterns associated with forged or manipulated images.

- Working Principle:<br>
These algorithms can detect inconsistencies, such as unnatural lighting, facial proportions that don't match, or signs of image manipulation.

### Reverse Image Search:

- Description: <br>
Platforms use reverse image search tools to check if a profile picture appears elsewhere on the internet, which may indicate that the image has been stolen or the identity is fake.

- Working : <br>
Principle: By comparing the uploaded image with a vast image database, the platform can identify instances of the same image being used across multiple user profiles.


### Self-Reporting Mechanism:

- Description:<br>
this is currently one of the most stable and effective ways to combat misuse. By establishing a reporting system and streamlining the reporting process, aided by AI-assisted review, the public is more willing to report violations. 

- Working Principle:<br>
Platforms integrate machine learning and human review, with machine learning automatically sifting through a large volume of reports, while human review teams further scrutinize potential false profiles to enhance detection accuracy.

## Concern

### Privacy Concerns

Users may worry about the extent to which their personal information is being scrutinized and used by the Al system.

### Erroneous Blocking 

Legitimate user accounts may be mistakenly flagged as fake and subsequently blocked.This can lead to incovenience and frustration for users who have their accounts restricted without just cause

### Restriction and Freedom of Speech

Excessive cencorship or overzeaolous application of the AI system could result in the suppression of content that is not fraudulent 

## Future technologies

### Enhance privacy protection measures

Develop AL technologies that are more transparent and respect user privacy.

### Enhance algorithmic accuracy

Continuously update and improve algorithms to minimize incorrect blocking of       legitimate account

### User Engagement and Feedback

Enable users to participate in identifying and reporting suspicious accounts to  improve system accuracy and effectiveness

### Ongoing Technical Monitoring and Evaluation
Regularly evaluate the effectiveness of the Ai system to ensure that it doesn’t infringe on users’ rights or restrict freedom of speech 


## Reference：

[fb關閉人臉識別技術](https://about.fb.com/news/2021/11/update-on-use-of-face-recognition/)

[圖像識別算法介紹](https://www.v7labs.com/blog/image-recognition-guide)

[去識別化資料](https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/index.html)







